//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Accessories
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public Nullable<decimal> CostRMB { get; set; }
        public Nullable<decimal> CostUSD { get; set; }
        public Nullable<decimal> PriceRMB { get; set; }
        public Nullable<decimal> PriceUSD { get; set; }
        public string PictureFolderPath { get; set; }
        public Nullable<int> SupplierID { get; set; }
    }
}
