//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Authority
    {
        public T_Authority()
        {
            this.T_Admin = new HashSet<T_Admin>();
        }
    
        public int ID { get; set; }
        public int AuthorityLevel { get; set; }
        public int AccesModuleID { get; set; }
    
        public virtual ICollection<T_Admin> T_Admin { get; set; }
        public virtual T_Module T_Module { get; set; }
    }
}
