//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Frame
    {
        public int ID { get; set; }
        public Nullable<int> FrameSNID { get; set; }
        public Nullable<int> ColorID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public Nullable<decimal> CostRMB { get; set; }
        public Nullable<decimal> PriceUSD { get; set; }
        public double LensWidth { get; set; }
        public double FrameWidth { get; set; }
        public double TempleLength { get; set; }
        public double NoseBridge { get; set; }
        public Nullable<double> Weight { get; set; }
        public Nullable<bool> IfSpring { get; set; }
        public Nullable<int> FrameTypeID { get; set; }
        public Nullable<int> FrameShapeID { get; set; }
        public Nullable<int> FrameMaterialID { get; set; }
        public Nullable<int> FrameSizeID { get; set; }
        public string InitialInformation { get; set; }
        public Nullable<bool> IfBiofocal { get; set; }
        public Nullable<int> FrameCategoryID { get; set; }
        public string FrameStyleIDs { get; set; }
        public Nullable<decimal> CostUSD { get; set; }
        public Nullable<decimal> PriceRMB { get; set; }
        public Nullable<int> SupplierID { get; set; }
        public string Other { get; set; }
        public string PictureFolderPath { get; set; }
        public Nullable<int> BrandID { get; set; }
        public Nullable<int> GenderID { get; set; }
        public Nullable<bool> IsPrepared { get; set; }
        public double LensHeight { get; set; }
        public string Description_CN { get; set; }
        public System.DateTime CreatDate { get; set; }
        public System.DateTime UpdateDate { get; set; }
    
        public virtual T_Brand T_Brand { get; set; }
        public virtual T_Color T_Color { get; set; }
        public virtual T_FrameCategory T_FrameCategory { get; set; }
        public virtual T_FrameMaterial T_FrameMaterial { get; set; }
        public virtual T_FrameShape T_FrameShape { get; set; }
        public virtual T_FrameSize T_FrameSize { get; set; }
        public virtual T_FrameSN T_FrameSN { get; set; }
        public virtual T_FrameStyle T_FrameStyle { get; set; }
        public virtual T_Supplier T_Supplier { get; set; }
        public virtual T_Gender T_Gender { get; set; }
    }
}
