//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Gender
    {
        public T_Gender()
        {
            this.T_User = new HashSet<T_User>();
            this.T_Frame = new HashSet<T_Frame>();
        }
    
        public int ID { get; set; }
        public string Gender { get; set; }
    
        public virtual ICollection<T_User> T_User { get; set; }
        public virtual ICollection<T_Frame> T_Frame { get; set; }
    }
}
