//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Lens
    {
        public int ID { get; set; }
        public Nullable<int> LensTypeID { get; set; }
        public Nullable<int> LensIndexID { get; set; }
        public Nullable<int> LensAdvancedID { get; set; }
        public Nullable<int> LensColorID { get; set; }
        public Nullable<decimal> LensCostRMB { get; set; }
        public Nullable<decimal> LensAdvancedPriceRMB { get; set; }
        public Nullable<decimal> LensTotalPriceUSD { get; set; }
        public Nullable<decimal> LensCostUSD { get; set; }
        public Nullable<decimal> LensTotalPriceRMB { get; set; }
        public Nullable<decimal> LensAdvancedPriceUSD { get; set; }
        public Nullable<int> SupplierID { get; set; }
    
        public virtual T_Color T_Color { get; set; }
        public virtual T_LensAdvanced T_LensAdvanced { get; set; }
        public virtual T_LensIndex T_LensIndex { get; set; }
        public virtual T_LensType T_LensType { get; set; }
        public virtual T_Supplier T_Supplier { get; set; }
    }
}
