//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Module
    {
        public T_Module()
        {
            this.T_Authority = new HashSet<T_Authority>();
        }
    
        public int ID { get; set; }
        public string ModuleName { get; set; }
    
        public virtual ICollection<T_Authority> T_Authority { get; set; }
    }
}
