//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Supplier
    {
        public T_Supplier()
        {
            this.T_Brand = new HashSet<T_Brand>();
            this.T_Frame = new HashSet<T_Frame>();
            this.T_Lens = new HashSet<T_Lens>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public string Address { get; set; }
        public string Telephone { get; set; }
        public string ZipCode { get; set; }
        public string Country { get; set; }
        public string Province { get; set; }
        public string City { get; set; }
        public string QQ { get; set; }
        public string MSN { get; set; }
        public string Website { get; set; }
        public string Other { get; set; }
        public string Goods { get; set; }
        public string LogoImg { get; set; }
    
        public virtual ICollection<T_Brand> T_Brand { get; set; }
        public virtual ICollection<T_Frame> T_Frame { get; set; }
        public virtual ICollection<T_Lens> T_Lens { get; set; }
    }
}
