//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_User
    {
        public T_User()
        {
            this.T_Admin = new HashSet<T_Admin>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public int GenderID { get; set; }
        public Nullable<int> Age { get; set; }
        public string Telephone { get; set; }
        public string Address { get; set; }
        public string QQ { get; set; }
        public string ZipCode { get; set; }
    
        public virtual ICollection<T_Admin> T_Admin { get; set; }
        public virtual T_Gender T_Gender { get; set; }
    }
}
